### PR TITLE
Add an example here to explain how the "filter" option works

### PR DESCRIPTION
**Pull request by leowzukw**
You may insert an expression selection all documents belonging to a set, an attribute, or located in a given folder.

Currently, the syntax of the `filter` attribute is quite unclear, I couldn't find how to use it after dozens of trial.

### CODE REVIEW

**Comment by zoggy** [comment]
This is indeed not documented yet, because it may be not stable. I did not use it a lot. By now, it is something like

````
EXPR::= <attribute>='<value>'
      | EXPR | EXPR
      | EXPR & EXPR
      | ! EXPR
      | ( EXPR )
````
The `<attribute>='<value>'` expressionis evaluated in the context of each document. Suppose you have a document like:
````xml
<page title="..." attr="foo' ...>
...
</page>
````
Then this document could be selected with the filter:
````xml
<documents ... filter="attr='foo'"/>
````
By now, content of attributs must be valid XML and because of escaping, you have to escape '&' to `&amp;amp;`, which is not very nice...

**Comment by leowzukw** [comment]
Thanks. It may interesting to insert a part of this answer in the documentation, especially the warning and the example.

**Comment by zoggy** [comment]
Will do for next release.

**Comment by leowzukw** [comment]
Great

**Pull request closed without merging**
